name: Test Build

on:
  schedule:
    - cron: '25 10 * * MON'
jobs:
  build:
    name: Example Build
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout the rpeository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        load: true
        tags: build-silabs
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build and deploy EI Model
      uses: edgeimpulse/build-deploy@v1
      id: build-deploy
      with:
        project_id: ${{ secrets.PROJECT_ID }}
        api_key: ${{ secrets.API_KEY }}
        deployment_type: 'slcc'

    - name: Extract the EI Model
      run: |
        unzip -q "${{ steps.build-deploy.outputs.deployment_file_name }}" -d extension
        rm -rf "${{ steps.build-deploy.outputs.deployment_file_name }}"

    - name: Build test app for BRD4166A
      run: |
        docker run --rm -v $PWD:/app build-silabs slc generate inference-example.slcp -d build_brd4166a -cp --toolchain=gcc --output-type=makefile --with=brd4166a
        docker run --rm -v $PWD:/app build-silabs make -C build_brd4166a -f inference-example.Makefile -j

    - name: Build test app for BRD2601B
      run: |
        docker run --rm -v $PWD:/app build-silabs slc generate inference-example.slcp -d build_brd2601b -cp --require-clean-project --toolchain=gcc --output-type=makefile --with=brd2601b
        docker run --rm -v $PWD:/app build-silabs make -C build_brd2601b -f inference-example.Makefile -j
